---
include:
  - board: corne_choc_pro_left//zmk
  - board: corne_choc_pro_right//zmk
  - board: corne_choc_pro_left//zmk
    shield: settings_reset
  - board: corne_choc_pro_right//zmk
    shield: settings_reset
